#!/bin/bash -eu
# Bootstrap script — symlinks dotfiles into $HOME and generates secret-bearing configs

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

# Load tokens from .env if present
if [ -f "$DOTFILES/.env" ]; then
  set -a
  . "$DOTFILES/.env"
  set +a
fi

symlink() {
  local src="$DOTFILES/$1"
  local dst="$HOME/$1"
  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    echo "SKIP  $dst (exists and is not a symlink)"
    return
  fi
  ln -sf "$src" "$dst"
  echo "LINK  $dst -> $src"
}

# Generate every profile's settings.json from settings.base.json + providers.json.
# Each provider entry supplies dir/aliases/token/baseUrl/models + freeform overrides;
# gen-settings.jq layers them onto the shared base. Adding a provider = one manifest entry.
generate_profiles() {
  local manifest="$DOTFILES/providers.json"
  local base; base="$(cat "$DOTFILES/settings.base.json")"
  local name
  for name in $(jq -r 'keys[]' "$manifest"); do
    local dir token_var token pentry
    dir="$(jq -r --arg n "$name" '.[$n].dir' "$manifest")"
    token_var="$(jq -r --arg n "$name" '.[$n].token // empty' "$manifest")"
    pentry="$(jq -c --arg n "$name" '.[$n]' "$manifest")"
    token=""
    [ -n "$token_var" ] && token="${!token_var:-}"

    mkdir -p "$HOME/$dir"
    symlink "$dir/CLAUDE.md"
    ln -sf "$DOTFILES/status-line.sh" "$HOME/$dir/status-line.sh"
    echo "LINK  $HOME/$dir/status-line.sh -> $DOTFILES/status-line.sh"
    jq -n --argjson base "$base" --argjson p "$pentry" --arg token "$token" \
      -f "$DOTFILES/gen-settings.jq" > "$HOME/$dir/settings.json"
    echo "GEN   $HOME/$dir/settings.json ($name)"
  done
}

# Generate the zsh wrapper fragment (sourced by .zshrc) from the same manifest:
# a `cl <provider>` dispatcher plus the short aliases (claude / s-claude / d-claude / …).
generate_zsh_profiles() {
  local manifest="$DOTFILES/providers.json"
  local out="$HOME/.claude-profiles.zsh"
  {
    echo "# AUTO-GENERATED by install.sh from providers.json — do not edit by hand."
    echo '_claude_with_profile() { export CLAUDE_CONFIG_DIR="$1"; command claude "${@:2}"; }'
    echo
    echo 'cl() {'
    echo '  local _p="${1:-default}"'
    echo "  if [[ \"\$_p\" == -l || \"\$_p\" == --list ]]; then print -l $(jq -r 'keys | join(" ")' "$manifest"); return 0; fi"
    echo '  local _dir'
    echo '  case "$_p" in'
    jq -r 'to_entries[] | "    \(.key)) _dir=\"\(.value.dir)\" ;;"' "$manifest"
    echo '    *) print "cl: unknown provider '\''$_p'\'' (try: cl --list)" >&2; return 1 ;;'
    echo '  esac'
    echo '  _claude_with_profile "$HOME/$_dir" "${@:2}"'
    echo '}'
    echo
    jq -r 'to_entries[] | .value as $v | $v.aliases[] | "\(.)() { _claude_with_profile \"$HOME/\($v.dir)\" \"$@\"; }"' "$manifest"
  } > "$out"
  echo "GEN   $out"
}

install_skills() {
  local skills_src="$DOTFILES/skills"
  local skills_dst="$HOME/.claude/skills"
  mkdir -p "$skills_dst"
  for skill_dir in "$skills_src"/*/; do
    local name
    name="$(basename "$skill_dir")"
    local dst="$skills_dst/$name"
    if [ -e "$dst" ]; then
      echo "SKIP  $dst (already exists)"
    else
      ln -s "$skill_dir" "$dst"
      echo "LINK  $dst -> $skill_dir"
    fi
  done
}

install_hooks() {
  local hooks_src="$DOTFILES/.claude/hooks"
  local hooks_dst="$HOME/.claude/hooks"
  [ -d "$hooks_src" ] || return 0
  mkdir -p "$hooks_dst"
  for hook in "$hooks_src"/*.sh; do
    [ -e "$hook" ] || continue
    local name dst
    name="$(basename "$hook")"
    dst="$hooks_dst/$name"
    ln -sf "$hook" "$dst"
    echo "LINK  $dst -> $hook"
  done
}

install_commands() {
  local commands_src="$DOTFILES/commands"
  [ -d "$commands_src" ] || return 0
  for profile in "${_claude_profiles[@]}"; do
    local commands_dst="$HOME/$profile/commands"
    mkdir -p "$commands_dst"
    for cmd in "$commands_src"/*.md; do
      [ -e "$cmd" ] || continue
      local name dst
      name="$(basename "$cmd")"
      dst="$commands_dst/$name"
      ln -sf "$cmd" "$dst"
      echo "LINK  $dst -> $cmd"
    done
  done
}

install_zsh_plugin() {
  local repo="$1"
  local name="${2:-$(basename "$repo" .git)}"
  local zsh_custom="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
  local plugin_dir="$zsh_custom/plugins/$name"

  if [ -d "$plugin_dir/.git" ]; then
    echo "SKIP  $name (already installed)"
    return
  fi

  mkdir -p "$zsh_custom/plugins"
  git clone --depth=1 "https://github.com/$repo.git" "$plugin_dir" 2>/dev/null
  echo "INST  $name plugin"
}

# Symlinks
symlink .zshrc
symlink .env.example

# Profiles + zsh wrappers — both driven by providers.json (single source of truth)
generate_profiles
generate_zsh_profiles

# Profile directories — used by install_commands to fan out shared commands
_claude_profiles=()
while IFS= read -r _dir; do _claude_profiles+=("$_dir"); done \
  < <(jq -r '.[].dir' "$DOTFILES/providers.json")

# Install skills into ~/.claude/skills (append-only)
install_skills

# Install hooks into ~/.claude/hooks (per-file symlinks, idempotent)
install_hooks

# Install shared slash commands into each profile's commands/ dir
install_commands

git -C "$DOTFILES" config core.hooksPath .githooks
echo "HOOK  core.hooksPath -> .githooks"

# Install custom zsh plugins (requires Oh My Zsh to be installed first)
install_zsh_plugin "zsh-users/zsh-autosuggestions"
install_zsh_plugin "zsh-users/zsh-syntax-highlighting"

echo "Done."
