#!/bin/bash -eu
# Bootstrap script — symlinks dotfiles into $HOME and generates secret-bearing configs

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load tokens from .env if present (override path via DOTFILES_ENV, e.g. for tests)
ENV_FILE="${DOTFILES_ENV:-$DOTFILES/.env}"
if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi

symlink() {
  local src="$DOTFILES/$1"
  local dst="$HOME/$1"
  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    echo "SKIP  $dst (exists and is not a symlink)"
    return
  fi
  ln -sf "$src" "$dst"
  echo "LINK  $dst -> $src"
}

# On macOS: plain ~/.zshrc symlink, so edits to the repo file are live
# immediately (no bwrap, so no symlink-resolution risk).
#
# On Linux (e.g. the bwrap sandbox for remote/orchestrated sessions): a REAL
# ~/.zshrc containing a `source "$DOTFILES/.zshrc"` line, NOT a symlink.
# bwrap follows symlinks when precomputing its tmpfs bind-mount points, so a
# symlink whose target isn't already in that list fails with ENOENT — the
# same failure mode the old ZDOTDIR-based ~/.zshenv (see git history) was
# built to avoid. A real file with a source line sidesteps it: bwrap only
# needs to resolve the two concrete paths involved (~/.zshrc itself and
# $DOTFILES/.zshrc), not walk a symlink to a directory that may not be
# mounted yet. RTK.md and the rtk hook stay Darwin-only regardless (see
# generate_profiles / providers.json) since rtk itself is a Homebrew-only
# binary — .zshrc has no rtk-specific content to begin with.
setup_zsh_config() {
  if [ "$(uname)" = "Linux" ]; then
    local dst="$HOME/.zshrc"
    local marker="source \"$DOTFILES/.zshrc\""
    if [ -e "$dst" ] && [ ! -L "$dst" ] && ! grep -qF "$marker" "$dst" 2>/dev/null; then
      echo "SKIP  $dst (exists and is not a symlink)"
      return
    fi
    [ -L "$dst" ] && rm -f "$dst"
    printf '%s\n' "$marker" > "$dst"
    echo "GEN   $dst ($marker)"
  else
    symlink .zshrc
  fi
}


# Generate every profile's settings.json from settings.base.json + providers.json.
# Each provider entry supplies dir/aliases/token/baseUrl/models + freeform overrides;
# gen-settings.jq layers them onto the shared base. Adding a provider = one manifest entry.
# Optional $1 restricts generation to a single provider name (used on Linux, which
# only gets the default profile — no zsh wrapper exists there to reach the others).
generate_profiles() {
  local only="${1:-}"
  local manifest="$DOTFILES/providers.json"
  local base; base="$(cat "$DOTFILES/settings.base.json")"
  local name
  for name in $(jq -r 'keys[]' "$manifest"); do
    [ -n "$only" ] && [ "$name" != "$only" ] && continue
    local dir token_var token pentry
    dir="$(jq -r --arg n "$name" '.[$n].dir' "$manifest")"
    token_var="$(jq -r --arg n "$name" '.[$n].token // empty' "$manifest")"
    pentry="$(jq -c --arg n "$name" '.[$n]' "$manifest")"
    token=""
    [ -n "$token_var" ] && token="${!token_var:-}"

    mkdir -p "$HOME/$dir"
    symlink "$dir/AGENTS.md"
    # RTK.md is macOS-only (rtk is a Homebrew package). On macOS with an RTK profile,
    # generate CLAUDE.md with @RTK.md included; everywhere else, symlink it as-is.
    if [ "$(uname)" = "Darwin" ] && [ -e "$DOTFILES/$dir/RTK.md" ]; then
      symlink "$dir/RTK.md"
      rm -f "$HOME/$dir/CLAUDE.md"
      printf '@AGENTS.md\n\n@RTK.md\n' > "$HOME/$dir/CLAUDE.md"
      echo "GEN   $HOME/$dir/CLAUDE.md (darwin+rtk)"
    else
      symlink "$dir/CLAUDE.md"
    fi
    ln -sf "$DOTFILES/status-line.sh" "$HOME/$dir/status-line.sh"
    echo "LINK  $HOME/$dir/status-line.sh -> $DOTFILES/status-line.sh"
    ln -sf "$DOTFILES/models.json" "$HOME/$dir/models.json"
    echo "LINK  $HOME/$dir/models.json -> $DOTFILES/models.json"
    jq -n --argjson base "$base" --argjson p "$pentry" --arg token "$token" \
      -f "$DOTFILES/gen-settings.jq" > "$HOME/$dir/settings.json"
    echo "GEN   $HOME/$dir/settings.json ($name)"
  done
}

# Generate the zsh wrapper fragment (sourced by .zshrc) from the same manifest:
# a `cl <provider>` dispatcher plus the short aliases (claude / s-claude / d-claude / …).
generate_zsh_profiles() {
  local manifest="$DOTFILES/providers.json"
  local out="$HOME/.claude-profiles.zsh"
  {
    echo "# AUTO-GENERATED by install.sh from providers.json — do not edit by hand."
    # No leading underscore: Claude Code's shell snapshot filters out `_*` functions,
    # which would break the `claude` wrapper inside its Bash tool.
    echo 'claude_with_profile() {'
    echo '  if ! command -v claude &>/dev/null; then'
    echo '    echo "cl: claude not on PATH (is it installed? brew bundle may help)" >&2'
    echo '    return 1'
    echo '  fi'
    echo '  export CLAUDE_CONFIG_DIR="$1"; command claude "${@:2}"'
    echo '}'
    echo
    echo 'cl() {'
    echo '  local _p="${1:-default}"'
    echo "  if [[ \"\$_p\" == -l || \"\$_p\" == --list ]]; then print -l $(jq -r 'keys | join(" ")' "$manifest"); return 0; fi"
    echo '  local _dir'
    echo '  case "$_p" in'
    jq -r 'to_entries[] | "    \(.key)) _dir=\"\(.value.dir)\" ;;"' "$manifest"
    echo '    *) print "cl: unknown provider '\''$_p'\'' (try: cl --list)" >&2; return 1 ;;'
    echo '  esac'
    echo '  claude_with_profile "$HOME/$_dir" "${@:2}"'
    echo '}'
    echo
    jq -r 'to_entries[] | .value as $v | $v.aliases[] | "\(.)() { claude_with_profile \"$HOME/\($v.dir)\" \"$@\"; }"' "$manifest"
  } > "$out"
  echo "GEN   $out"
}

install_skills() {
  local skills_src="$DOTFILES/skills"
  local skills_dst="$HOME/.claude/skills"
  mkdir -p "$skills_dst"
  for skill_dir in "$skills_src"/*/; do
    local name dst
    name="$(basename "$skill_dir")"
    dst="$skills_dst/$name"
    # Leave a real (manually installed) dir alone; repair stale/dangling symlinks.
    # -n so an existing symlink-to-dir is replaced, not followed into.
    if [ -e "$dst" ] && [ ! -L "$dst" ]; then
      echo "SKIP  $dst (exists and is not a symlink)"
      continue
    fi
    ln -sfn "$skill_dir" "$dst"
    echo "LINK  $dst -> $skill_dir"
  done
}

install_plugin_lock() {
  mkdir -p "$HOME/.claude/plugins"
  # Copy and expand ~ → $HOME so installPath values are valid absolute paths on
  # this machine. A symlink would let Claude Code write machine-specific paths
  # back into the committed file; a copy keeps the repo file as a pinned snapshot.
  sed "s|~|$HOME|g" "$DOTFILES/installed_plugins.json" \
    > "$HOME/.claude/plugins/installed_plugins.json"
  echo "COPY  $HOME/.claude/plugins/installed_plugins.json (paths expanded for $HOME)"
}

# Weekday-9am launchd agent that runs scripts/daily-session-log.sh — logs each
# Claude Code session under ~/work into the latest weekly note and opens a PR.
# Work-machine only (like the skill-scan guard), and only when a ~/work/notes git
# checkout exists; the script itself self-guards on GEMINI_API_KEY and the repo.
install_session_log_agent() {
  if [ "$(hostname -s)" != "$WORK_HOSTNAME" ]; then
    echo "SKIP  daily-session-log agent (non-work machine)"
    return 0
  fi
  if [ ! -d "$HOME/work/notes/.git" ]; then
    echo "SKIP  daily-session-log agent (~/work/notes not a git checkout)"
    return 0
  fi
  local label="com.$(id -un).daily-session-log"
  local plist="$HOME/Library/LaunchAgents/$label.plist"
  local script="$DOTFILES/scripts/daily-session-log.sh"
  local logdir="$HOME/.claude/logs"
  mkdir -p "$HOME/Library/LaunchAgents" "$logdir"

  # Five StartCalendarInterval entries (Weekday 1..5 = Mon..Fri) at 09:00.
  local weekdays=""
  local d
  for d in 1 2 3 4 5; do
    weekdays+="    <dict><key>Weekday</key><integer>$d</integer><key>Hour</key><integer>9</integer><key>Minute</key><integer>0</integer></dict>
"
  done

  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$script</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>
$weekdays  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>$logdir/daily-session-log.log</string>
  <key>StandardErrorPath</key><string>$logdir/daily-session-log.log</string>
</dict>
</plist>
PLIST
  echo "GEN   $plist"

  # Reload so schedule/env changes take effect (ignore unload error on first install).
  launchctl unload "$plist" 2>/dev/null || true
  if launchctl load -w "$plist" 2>/dev/null; then
    echo "LOAD  $label (weekdays 09:00)"
  else
    echo "WARN  could not launchctl load $label — load it manually"
  fi
}

install_hooks() {
  local hooks_src="$DOTFILES/.claude/hooks"
  local hooks_dst="$HOME/.claude/hooks"
  [ -d "$hooks_src" ] || return 0
  mkdir -p "$hooks_dst"
  for hook in "$hooks_src"/*.sh; do
    [ -e "$hook" ] || continue
    local name dst
    name="$(basename "$hook")"
    dst="$hooks_dst/$name"
    ln -sf "$hook" "$dst"
    echo "LINK  $dst -> $hook"
  done
}

install_commands() {
  local commands_src="$DOTFILES/commands"
  [ -d "$commands_src" ] || return 0
  for profile in "${_claude_profiles[@]}"; do
    local commands_dst="$HOME/$profile/commands"
    mkdir -p "$commands_dst"
    for cmd in "$commands_src"/*.md; do
      [ -e "$cmd" ] || continue
      local name dst
      name="$(basename "$cmd")"
      dst="$commands_dst/$name"
      ln -sf "$cmd" "$dst"
      echo "LINK  $dst -> $cmd"
    done
  done
}

install_zsh_plugin() {
  local repo="$1"
  local name="${2:-$(basename "$repo" .git)}"
  local tag="$3"
  local expected_sha="$4"
  local zsh_custom="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
  local plugin_dir="$zsh_custom/plugins/$name"

  if [ -d "$plugin_dir/.git" ]; then
    echo "SKIP  $name (already installed)"
    return
  fi

  mkdir -p "$zsh_custom/plugins"
  git clone --depth=1 --branch "$tag" "https://github.com/$repo.git" "$plugin_dir" 2>/dev/null
  local actual
  actual=$(git -C "$plugin_dir" rev-parse HEAD)
  [ "$actual" = "$expected_sha" ] || { echo "ERR   SHA mismatch for $repo (got $actual, want $expected_sha)"; exit 1; }
  echo "INST  $name plugin ($tag)"
}

# Install pinned npm CLI tools (ccusage, …) from tools/package-lock.json.
# `npm ci` verifies each tarball against the lockfile's sha512 integrity pin,
# so this is the npm equivalent of the zsh plugin SHA pins. Binaries are
# symlinked into ~/.local/bin (already on PATH via .zshrc).
# To bump a tool: edit tools/package.json, run `npm install --package-lock-only`
# in tools/, commit both files, re-run ./install.sh.
install_node_tools() {
  local tools_dir="$DOTFILES/tools"

  [ -n "${DOTFILES_SKIP_NODE_TOOLS:-}" ] && { echo "SKIP  node tools (DOTFILES_SKIP_NODE_TOOLS set)"; return; }
  command -v npm >/dev/null || { echo "SKIP  node tools (npm not found)"; return; }

  # npm ci wipes node_modules every run; skip when already in sync with the lockfile
  if (cd "$tools_dir" && npm ls --omit=dev >/dev/null 2>&1); then
    echo "SKIP  node tools (in sync with lockfile)"
  else
    (cd "$tools_dir" && npm ci --no-audit --no-fund >/dev/null)
    echo "INST  node tools (npm ci, integrity verified)"
  fi

  mkdir -p "$HOME/.local/bin"
  local bin
  for bin in "$tools_dir/node_modules/.bin"/*; do
    [ -e "$bin" ] || continue
    ln -sf "$bin" "$HOME/.local/bin/$(basename "$bin")"
    echo "LINK  $HOME/.local/bin/$(basename "$bin") -> $bin"
  done
}

# When sourced (e.g. by tests that want a single function), stop here so only
# the function definitions above load and none of the install steps below run.
[ "${BASH_SOURCE[0]}" != "${0}" ] && return 0

# These are primarily macOS/zsh dotfiles. On Linux (e.g. the bwrap sandbox used
# by remote/orchestrated sessions) the multi-profile machinery still doesn't
# apply — there's no zsh wrapper there to reach a second or third profile — but
# ~/.zshrc (see setup_zsh_config) and the Claude Code side (default-profile
# settings.json, hooks, skills, commands) are both wanted, so that subset
# installs there too, straight into the real ~/.claude. reset-linux.sh is
# the matching undo for exactly this subset.
IS_DARWIN=0
[ "$(uname)" = "Darwin" ] && IS_DARWIN=1

# Work-machine detection — gates the skill-scan guard and the personal sonnet switch.
# Override via DOTFILES_WORK_HOSTNAME if your work hostname differs from the default.
WORK_HOSTNAME="${DOTFILES_WORK_HOSTNAME:-Shuis-MacBook-Air}"

setup_zsh_config
symlink .env.example

# Profiles + zsh wrappers — both driven by providers.json (single source of truth).
# Linux only ever gets the "default" profile (see comment above).
if [ "$IS_DARWIN" = 1 ]; then
  generate_profiles
  generate_zsh_profiles
  # Profile directories — used by install_commands to fan out shared commands
  _claude_profiles=()
  while IFS= read -r _dir; do _claude_profiles+=("$_dir"); done \
    < <(jq -r '.[].dir' "$DOTFILES/providers.json")
else
  generate_profiles default
  _claude_profiles=(".claude")
fi

# Install skills into ~/.claude/skills (append-only)
install_skills

# Install hooks into ~/.claude/hooks (per-file symlinks, idempotent)
install_hooks

# Install shared slash commands into each profile's commands/ dir
install_commands

if [ "$IS_DARWIN" = 1 ]; then
  # Symlink plugin lock so installed SHAs are pinned across machines. Skipped on
  # Linux: the pinned versions/paths are macOS-cache-specific and installing
  # plugins there is a separate, heavier step than this settings/hooks parity fix.
  install_plugin_lock

  git -C "$DOTFILES" config core.hooksPath .githooks
  echo "HOOK  core.hooksPath -> .githooks"

  # Install custom zsh plugins (requires Oh My Zsh to be installed first)
  install_zsh_plugin "zsh-users/zsh-autosuggestions" "" "v0.7.1" "e52ee8ca55bcc56a17c828767a3f98f22a68d4eb"
  install_zsh_plugin "zsh-users/zsh-syntax-highlighting" "" "0.8.0" "db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e"

  # Install pinned npm CLI tools from tools/package-lock.json
  install_node_tools

  # Weekday-9am session-log launchd agent (self-skips without ~/work/notes)
  install_session_log_agent
fi

# Pre-warm Trivy's vulnerability DB for the work-laptop skill-scan guard
# (.claude/hooks/skill-scan-guard.sh) so scans run offline at hook time. Trivy
# needs no token — secret/misconfig scanning is already offline; this just caches
# the vuln DB locally. Work machine only, and only if trivy is installed.
if [ "$(hostname -s)" = "$WORK_HOSTNAME" ]; then
  if command -v trivy >/dev/null 2>&1; then
    if trivy fs --download-db-only -q >/dev/null 2>&1; then
      echo "OK    trivy vuln DB pre-warmed (skill-scan)"
    else
      echo "WARN  trivy DB download failed — first skill-scan will fetch it"
    fi
  else
    echo "WARN  trivy not installed — run 'brew bundle' so the skill-scan guard can vet installs"
  fi
else
  echo "SKIP  trivy DB pre-warm (non-work machine)"
fi

# Personal laptops use sonnet (lower subscription limits); work machine keeps the manifest model.
if [ "$(hostname -s)" != "$WORK_HOSTNAME" ]; then
  jq '.model = "sonnet"' "$HOME/.claude/settings.json" > "$HOME/.claude/settings.json.tmp" \
    && mv "$HOME/.claude/settings.json.tmp" "$HOME/.claude/settings.json"
  echo "SET   $HOME/.claude/settings.json model -> sonnet (personal)"
else
  manifest_model=$(jq -r '.model' "$HOME/.claude/settings.json")
  echo "SKIP  sonnet switch (work machine — keeping $manifest_model)"
fi

echo "Done."
