#!/bin/bash -eu
# Bootstrap script — symlinks dotfiles into $HOME and generates secret-bearing configs

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

# Load tokens from .env if present (override path via DOTFILES_ENV, e.g. for tests)
ENV_FILE="${DOTFILES_ENV:-$DOTFILES/.env}"
if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi

symlink() {
  local src="$DOTFILES/$1"
  local dst="$HOME/$1"
  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    echo "SKIP  $dst (exists and is not a symlink)"
    return
  fi
  ln -sf "$src" "$dst"
  echo "LINK  $dst -> $src"
}

# Generate every profile's settings.json from settings.base.json + providers.json.
# Each provider entry supplies dir/aliases/token/baseUrl/models + freeform overrides;
# gen-settings.jq layers them onto the shared base. Adding a provider = one manifest entry.
generate_profiles() {
  local manifest="$DOTFILES/providers.json"
  local base; base="$(cat "$DOTFILES/settings.base.json")"
  local name
  for name in $(jq -r 'keys[]' "$manifest"); do
    local dir token_var token pentry
    dir="$(jq -r --arg n "$name" '.[$n].dir' "$manifest")"
    token_var="$(jq -r --arg n "$name" '.[$n].token // empty' "$manifest")"
    pentry="$(jq -c --arg n "$name" '.[$n]' "$manifest")"
    token=""
    [ -n "$token_var" ] && token="${!token_var:-}"

    mkdir -p "$HOME/$dir"
    symlink "$dir/CLAUDE.md"
    symlink "$dir/AGENTS.md"
    ln -sf "$DOTFILES/status-line.sh" "$HOME/$dir/status-line.sh"
    echo "LINK  $HOME/$dir/status-line.sh -> $DOTFILES/status-line.sh"
    jq -n --argjson base "$base" --argjson p "$pentry" --arg token "$token" \
      -f "$DOTFILES/gen-settings.jq" > "$HOME/$dir/settings.json"
    echo "GEN   $HOME/$dir/settings.json ($name)"
  done
}

# Generate the zsh wrapper fragment (sourced by .zshrc) from the same manifest:
# a `cl <provider>` dispatcher plus the short aliases (claude / s-claude / d-claude / …).
generate_zsh_profiles() {
  local manifest="$DOTFILES/providers.json"
  local out="$HOME/.claude-profiles.zsh"
  {
    echo "# AUTO-GENERATED by install.sh from providers.json — do not edit by hand."
    # No leading underscore: Claude Code's shell snapshot filters out `_*` functions,
    # which would break the `claude` wrapper inside its Bash tool.
    echo 'claude_with_profile() { export CLAUDE_CONFIG_DIR="$1"; command claude "${@:2}"; }'
    echo
    echo 'cl() {'
    echo '  local _p="${1:-default}"'
    echo "  if [[ \"\$_p\" == -l || \"\$_p\" == --list ]]; then print -l $(jq -r 'keys | join(" ")' "$manifest"); return 0; fi"
    echo '  local _dir'
    echo '  case "$_p" in'
    jq -r 'to_entries[] | "    \(.key)) _dir=\"\(.value.dir)\" ;;"' "$manifest"
    echo '    *) print "cl: unknown provider '\''$_p'\'' (try: cl --list)" >&2; return 1 ;;'
    echo '  esac'
    echo '  claude_with_profile "$HOME/$_dir" "${@:2}"'
    echo '}'
    echo
    jq -r 'to_entries[] | .value as $v | $v.aliases[] | "\(.)() { claude_with_profile \"$HOME/\($v.dir)\" \"$@\"; }"' "$manifest"
  } > "$out"
  echo "GEN   $out"
}

install_skills() {
  local skills_src="$DOTFILES/skills"
  local skills_dst="$HOME/.claude/skills"
  mkdir -p "$skills_dst"
  for skill_dir in "$skills_src"/*/; do
    local name dst
    name="$(basename "$skill_dir")"
    dst="$skills_dst/$name"
    # Leave a real (manually installed) dir alone; repair stale/dangling symlinks.
    # -n so an existing symlink-to-dir is replaced, not followed into.
    if [ -e "$dst" ] && [ ! -L "$dst" ]; then
      echo "SKIP  $dst (exists and is not a symlink)"
      continue
    fi
    ln -sfn "$skill_dir" "$dst"
    echo "LINK  $dst -> $skill_dir"
  done
}

# Routines (scheduled cloud agents) are work-specific: restore them only on the
# work machine so personal laptops never pick up work schedules. Same semantics
# as install_skills — real dirs are left alone, symlinks are created/repaired.
install_routines() {
  local routines_src="$DOTFILES/routines"
  local routines_dst="$HOME/.claude/scheduled-tasks"
  [ -d "$routines_src" ] || return 0
  if [ "$(hostname -s)" != "$WORK_HOSTNAME" ]; then
    echo "SKIP  routines (non-work machine)"
    return 0
  fi
  mkdir -p "$routines_dst"
  # Prune symlinks pointing into routines/ whose source dir is gone
  # (routine was deleted server-side and removed by /sync-routines)
  for link in "$routines_dst"/*; do
    [ -L "$link" ] || continue
    case "$(readlink "$link")" in
      "$routines_src"/*)
        if [ ! -e "$link" ]; then
          rm "$link"
          echo "PRUNE $link"
        fi
        ;;
    esac
  done
  for routine_dir in "$routines_src"/*/; do
    local name dst
    name="$(basename "$routine_dir")"
    dst="$routines_dst/$name"
    if [ -e "$dst" ] && [ ! -L "$dst" ]; then
      echo "SKIP  $dst (exists and is not a symlink)"
      continue
    fi
    ln -sfn "$routine_dir" "$dst"
    echo "LINK  $dst -> $routine_dir"
  done
}

install_plugin_lock() {
  mkdir -p "$HOME/.claude/plugins"
  ln -sf "$DOTFILES/installed_plugins.json" "$HOME/.claude/plugins/installed_plugins.json"
  echo "LINK  $HOME/.claude/plugins/installed_plugins.json -> $DOTFILES/installed_plugins.json"
}

install_hooks() {
  local hooks_src="$DOTFILES/.claude/hooks"
  local hooks_dst="$HOME/.claude/hooks"
  [ -d "$hooks_src" ] || return 0
  mkdir -p "$hooks_dst"
  for hook in "$hooks_src"/*.sh; do
    [ -e "$hook" ] || continue
    local name dst
    name="$(basename "$hook")"
    dst="$hooks_dst/$name"
    ln -sf "$hook" "$dst"
    echo "LINK  $dst -> $hook"
  done
}

install_commands() {
  local commands_src="$DOTFILES/commands"
  [ -d "$commands_src" ] || return 0
  for profile in "${_claude_profiles[@]}"; do
    local commands_dst="$HOME/$profile/commands"
    mkdir -p "$commands_dst"
    for cmd in "$commands_src"/*.md; do
      [ -e "$cmd" ] || continue
      local name dst
      name="$(basename "$cmd")"
      dst="$commands_dst/$name"
      ln -sf "$cmd" "$dst"
      echo "LINK  $dst -> $cmd"
    done
  done
}

install_zsh_plugin() {
  local repo="$1"
  local name="${2:-$(basename "$repo" .git)}"
  local tag="$3"
  local expected_sha="$4"
  local zsh_custom="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
  local plugin_dir="$zsh_custom/plugins/$name"

  if [ -d "$plugin_dir/.git" ]; then
    echo "SKIP  $name (already installed)"
    return
  fi

  mkdir -p "$zsh_custom/plugins"
  git clone --depth=1 --branch "$tag" "https://github.com/$repo.git" "$plugin_dir" 2>/dev/null
  local actual
  actual=$(git -C "$plugin_dir" rev-parse HEAD)
  [ "$actual" = "$expected_sha" ] || { echo "ERR   SHA mismatch for $repo (got $actual, want $expected_sha)"; exit 1; }
  echo "INST  $name plugin ($tag)"
}

# Install pinned npm CLI tools (ccusage, …) from tools/package-lock.json.
# `npm ci` verifies each tarball against the lockfile's sha512 integrity pin,
# so this is the npm equivalent of the zsh plugin SHA pins. Binaries are
# symlinked into ~/.local/bin (already on PATH via .zshrc).
# To bump a tool: edit tools/package.json, run `npm install --package-lock-only`
# in tools/, commit both files, re-run ./install.sh.
install_node_tools() {
  local tools_dir="$DOTFILES/tools"

  [ -n "${DOTFILES_SKIP_NODE_TOOLS:-}" ] && { echo "SKIP  node tools (DOTFILES_SKIP_NODE_TOOLS set)"; return; }
  command -v npm >/dev/null || { echo "SKIP  node tools (npm not found)"; return; }

  # npm ci wipes node_modules every run; skip when already in sync with the lockfile
  if (cd "$tools_dir" && npm ls --omit=dev >/dev/null 2>&1); then
    echo "SKIP  node tools (in sync with lockfile)"
  else
    (cd "$tools_dir" && npm ci --no-audit --no-fund >/dev/null)
    echo "INST  node tools (npm ci, integrity verified)"
  fi

  mkdir -p "$HOME/.local/bin"
  local bin
  for bin in "$tools_dir/node_modules/.bin"/*; do
    [ -e "$bin" ] || continue
    ln -sf "$bin" "$HOME/.local/bin/$(basename "$bin")"
    echo "LINK  $HOME/.local/bin/$(basename "$bin") -> $bin"
  done
}

# Work-machine detection — gates routine restore and the personal sonnet switch.
# Override via DOTFILES_WORK_HOSTNAME if your work hostname differs from the default.
WORK_HOSTNAME="${DOTFILES_WORK_HOSTNAME:-Shuis-MacBook-Air}"

# Symlinks
symlink .zshrc
symlink .env.example

# Profiles + zsh wrappers — both driven by providers.json (single source of truth)
generate_profiles
generate_zsh_profiles

# Profile directories — used by install_commands to fan out shared commands
_claude_profiles=()
while IFS= read -r _dir; do _claude_profiles+=("$_dir"); done \
  < <(jq -r '.[].dir' "$DOTFILES/providers.json")

# Install skills into ~/.claude/skills (append-only)
install_skills

# Install hooks into ~/.claude/hooks (per-file symlinks, idempotent)
install_hooks

# Restore routines into ~/.claude/scheduled-tasks (work machine only)
install_routines

# Symlink plugin lock so installed SHAs are pinned across machines
install_plugin_lock

# Install shared slash commands into each profile's commands/ dir
install_commands

git -C "$DOTFILES" config core.hooksPath .githooks
echo "HOOK  core.hooksPath -> .githooks"

# Install custom zsh plugins (requires Oh My Zsh to be installed first)
install_zsh_plugin "zsh-users/zsh-autosuggestions" "" "v0.7.1" "e52ee8ca55bcc56a17c828767a3f98f22a68d4eb"
install_zsh_plugin "zsh-users/zsh-syntax-highlighting" "" "0.8.0" "db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e"

# Install pinned npm CLI tools from tools/package-lock.json
install_node_tools

# Personal laptops use sonnet (lower subscription limits); work machine keeps the manifest model.
if [ "$(hostname -s)" != "$WORK_HOSTNAME" ]; then
  jq '.model = "sonnet"' "$HOME/.claude/settings.json" > "$HOME/.claude/settings.json.tmp" \
    && mv "$HOME/.claude/settings.json.tmp" "$HOME/.claude/settings.json"
  echo "SET   $HOME/.claude/settings.json model -> sonnet (personal)"
else
  manifest_model=$(jq -r '.model' "$HOME/.claude/settings.json")
  echo "SKIP  sonnet switch (work machine — keeping $manifest_model)"
fi

echo "Done."
